// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvmnoofmuqwlvprgxvtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bW5vb2ZtdXF3bHZwcmd4dnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MTQ1OTIsImV4cCI6MjA5MDA5MDU5Mn0.rjvR7HTEGpGwK7rR4MGkvTaI_Zq9SytGKW-Lq_UrSao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
