// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbvgkghaflpudjxutban.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidmdrZ2hhZmxwdWRqeHV0YmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTE0MzcsImV4cCI6MjA2NTI4NzQzN30.jNyska9b1-Lh3fbG7Leco8SBRywpQuBP1qied6ZQ8Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);